### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by khmarbaise** [simasch/angular-springboot-demo#1]
https://github.com/simasch/angular-springboot-demo/blob/be0b3e5cbf72779478ea465350f0308148ffd549/backend/src/test/java/ch/martinelli/demo/backend/person/PersonControllerTest.java

I've taken a look into `PersonControllerTest`. The method `beforeAll` is annotated with `@BeforeEach` doesn't that mean that for each test the attributes are created from scratch (creating a new instance of the whole test class) which means the `header` will always `null` which in consequence meanse the `if (header == null)` is superflous?

**Comment by simasch** [comment]
Hi @khmarbaise 
Thanks for pointing that out!
I adjusted the code accordingly.
